name: protracker
base: core18
summary: A ProTracker 2.3D clone
description: |
  A multi-platform clone of the classic music making software ProTracker
  from the Commodore Amiga days.
grade: stable
confinement: strict
adopt-info: protracker

apps:
  protracker:
    command: usr/bin/protracker
    plugs:
      - home
      - alsa
      - pulseaudio
      - x11
      - wayland
      - opengl
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

parts:
  protracker:
    plugin: nil
    source: https://github.com/8bitbubsy/pt2-clone
    source-type: git
    after:
      - patches
    build-packages:
      - make
      - gcc
      - libsdl2-dev
    stage-packages:
      - libsdl2-2.0-0
    override-pull: |
      snapcraftctl pull
      version="$(sed -n '/PROG_VER_STR/s/.*"\(.*\)"/\1/p' < src/pt2_header.h)-$(git rev-parse --short HEAD)"
      snapcraftctl set-version "$version"
      patch -d "$SNAPCRAFT_PART_SRC" -p0 < "$SNAPCRAFT_STAGE"/fix-config-dir.patch
      patch -d "$SNAPCRAFT_PART_SRC" -p1 < "$SNAPCRAFT_STAGE"/build-generic-binary.patch
    override-build: |
      sh make-linux.sh
      cp release/other/pt2-clone "$SNAPCRAFT_PART_INSTALL"/usr/bin/protracker
    prime:
      - -usr/share/doc
      - -usr/share/man
    
  patches:
    plugin: dump
    source: patches
    prime:
      - -*

