name: protracker
base: core22
summary: A ProTracker 2.3D clone
description: |
  A multi-platform clone of the classic music making software ProTracker
  from the Commodore Amiga days.
grade: stable
confinement: strict
adopt-info: protracker

apps:
  protracker:
    command: usr/bin/protracker
    command-chain: [pulse-runner]
    plugs:
      - home
      - alsa
      - pulseaudio
      - x11
      - wayland
      - opengl
      - audio-playback
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio

parts:
  protracker:
    plugin: nil
    source: https://github.com/8bitbubsy/pt2-clone.git
    build-packages:
      - make
      - gcc
      - libsdl2-dev
    stage-packages:
      - libsdl2-2.0-0
    override-pull: |
      craftctl default
      version="$(sed -n '/PROG_VER_STR/s/.*"\(.*\)"/\1/p' < src/pt2_header.h)-$(git rev-parse --short HEAD)"
      craftctl set version="$version"
      patch -d "$CRAFT_PART_SRC" -p0 < "$CRAFT_PROJECT_DIR"/patches/fix-config-dir.patch
      patch -d "$CRAFT_PART_SRC" -p1 < "$CRAFT_PROJECT_DIR"/patches/build-generic-binary.patch
    override-build: |
      sh make-linux.sh
      cp release/other/pt2-clone "$CRAFT_PART_INSTALL"/usr/bin/protracker
      cp "$CRAFT_PROJECT_DIR"/scripts/pulse-runner "$CRAFT_PART_INSTALL"
    prime:
      - -usr/share/doc
      - -usr/share/man

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
